
# Port configuration
server.port=${SERVER_PORT:4000}

# Database configuration - H2 Database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA and Hibernate configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.sql.init.mode=${SPRING_SQL_INIT_MODE}

billing.service.address=${BILLING_SERVICE_ADDRESS:localhost:4001}
billing.service.grpc.port=${BILLING_SERVICE_GRPC_PORT:9001}

spring.kafka.topic.patient=${SPRING_KAFKA_TOPIC_PATIENT}
spring.kafka.producer.key-serializer=${SPRING_KAFKA_PRODUCER_KEY_SERIALIZER}
spring.kafka.producer.value-serializer=${SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER}
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}


logging.level.root=INFO
