
# Port configuration
server.port=4000

# Database configuration - H2 Database
spring.datasource.url=jdbc:h2:mem:patientDb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin_viewer
spring.datasource.password=password

# JPA and Hibernate configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always