
# Port configuration
server.port=${SERVER_PORT:4000}

# Database configuration - H2 Database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA and Hibernate configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.sql.init.mode=${SPRING_SQL_INIT_MODE}

logging.level.root=INFO
