name: Deploy Patient Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy Patient Service
        run: |
          cd /home/dilshanjay/Apps/patient-management/patient-service

          echo "Updating repository..."
          git fetch origin
          git reset --hard origin/main

          cd ..

          echo "Building Docker image..."
          docker compose build patient-service

          echo "Restarting container..."
          docker compose up -d patient-service

          echo "Deployment completed!"