name: Deploy Patient Service

on:
  workflow_run:
    workflows: ["Build and Publish Docker Image"]
    types:
      - completed

jobs:
  deploy:
    # Only deploy if the build workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: self-hosted

    steps:
      - name: Deploy Patient Service
        run: |
          cd /home/dilshanjay/Apps/patient-management/patient-service

          echo "Updating repository..."
          git fetch origin
          git reset --hard origin/main

          cd ..

          echo "Pulling latest Docker image..."
          docker compose pull patient-service

          echo "Restarting container..."
          docker compose up -d patient-service

          echo "Deployment completed!"